// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCifn71ZDbcAcHtU5Jtt4pstYme9hlBiCY',
    appId: '1:934002492238:web:c04ed52566fb6b7344941f',
    messagingSenderId: '934002492238',
    projectId: 'bycatering-19539',
    authDomain: 'bycatering-19539.firebaseapp.com',
    storageBucket: 'bycatering-19539.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZGJBIgeIdSCJVogpVzKvD4-WW0_iWes',
    appId: '1:934002492238:android:c6c227b41a82813c44941f',
    messagingSenderId: '934002492238',
    projectId: 'bycatering-19539',
    storageBucket: 'bycatering-19539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQZQegWZN8y-Hgira_yhkROJiz69hCY2U',
    appId: '1:934002492238:ios:d4ac8c7e156e8d3944941f',
    messagingSenderId: '934002492238',
    projectId: 'bycatering-19539',
    storageBucket: 'bycatering-19539.appspot.com',
    iosClientId: '934002492238-ul6djmgtj9tb4gqbbuoe96j64t9gk6ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.bycatering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQZQegWZN8y-Hgira_yhkROJiz69hCY2U',
    appId: '1:934002492238:ios:d4ac8c7e156e8d3944941f',
    messagingSenderId: '934002492238',
    projectId: 'bycatering-19539',
    storageBucket: 'bycatering-19539.appspot.com',
    iosClientId: '934002492238-ul6djmgtj9tb4gqbbuoe96j64t9gk6ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.bycatering',
  );
}
